---
- name: Install OpenCV
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - build-essential
          - cmake
          - git
          - pkg-config
          - libgtk-3-dev
          - libavcodec-dev
          - libavformat-dev
          - libswscale-dev
          - libv4l-dev
          - libxvidcore-dev
          - libx264-dev
          - libjpeg-dev
          - libpng-dev
          - libtiff-dev
          - gfortran
          - openexr
          - libatlas-base-dev
          - python3-dev
          - python3-numpy
          - libtbb2
          - libtbb-dev
          - libdc1394-dev
          - libopenexr-dev
          - libgstreamer-plugins-base1.0-dev
          - libgstreamer1.0-dev
          - libhdf5-dev
        state: present
        update_cache: yes

    - name: Clone OpenCV repository
      git:
        repo: https://github.com/opencv/opencv.git
        dest: /tmp/opencv
        version: master

    - name: Clone OpenCV contrib repository
      git:
        repo: https://github.com/opencv/opencv_contrib.git
        dest: /tmp/opencv_contrib
        version: master

    - name: Create build directory
      file:
        path: /tmp/opencv/build
        state: directory

    - name: Configure OpenCV build with CMake
      command: >
        cmake -D CMAKE_BUILD_TYPE=RELEASE
              -D CMAKE_INSTALL_PREFIX=/usr/local
              -D INSTALL_C_EXAMPLES=ON
              -D INSTALL_PYTHON_EXAMPLES=ON
              -D OPENCV_GENERATE_PKGCONFIG=ON
              -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_contrib/modules
              -D BUILD_EXAMPLES=ON
              ..
      args:
        chdir: /tmp/opencv/build

    - name: Build OpenCV
      command: make -j8
      args:
        chdir: /tmp/opencv/build

    - name: Install OpenCV
      command: make install
      args:
        chdir: /tmp/opencv/build

    - name: Verify OpenCV installation
      command: pkg-config --modversion opencv4
      register: opencv_version

    - name: Display OpenCV version
      debug:
        msg: "OpenCV version installed: {{ opencv_version.stdout }}"
